<?php
function Create_All_Tables($conn)
{

  $sql = "CREATE TABLE IF NOT EXISTS CANDIDATE(
      CANDIDATE_ID INT(32),
      FIRST_NAME VARCHAR(30),
      LAST_NAME VARCHAR(30),
      AGE INT(32),
      DATE_OF_REGRISTRATION DATE,
      JOB_HISTORY INT,
      COURSE_TAKING INT,
      QUALIFICATION_CODE INT,
      PRIMARY KEY (CANDIDATE_ID)
    ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
    
    CREATE TABLE IF NOT EXISTS COMPANY(
      COMPANY_ID INT(32),
      COMPANY_TEXT VARCHAR(50),
      EMPLOYEES_REQUESTING INT,
      OPENING_ID INT,
      PRIMARY KEY (COMPANY_ID)
      ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

      CREATE TABLE IF NOT EXISTS COURSE(
      COURSE_ID INT(32),
      SESSION_ID INT(32),
      PREREQUISITES VARCHAR(50),
      QUALIFICATION_CODE VARCHAR(50),
      PRIMARY KEY(COURSE_ID)
      ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

      CREATE TABLE IF NOT EXISTS JOB_HISTORY(
      CANDIDATE_ID INT(32),
      PAST_JOB VARCHAR(50),
      PRIMARY KEY (CANDIDATE_ID)
      ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

      CREATE TABLE IF NOT EXISTS OPENING(
      OPENING_ID INT(32),
      COMPANY_ID INT(32),
      COMPANY_NAME VARCHAR(200),
      STARTING_DATE DATE,
      MAIN_QUALIFICATION VARCHAR(11),
      REQUIRED_QUALIFCATIONS INT,
      PRIMARY KEY (OPENING_ID)
      ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

      CREATE TABLE IF NOT EXISTS QUALIFICATION(
      QUALIFICATION_CODE VARCHAR(50),
      COURSE_ID INT(32),
      DESCRIPTION VARCHAR(200),
      PRIMARY KEY (QUALIFICATION_CODE)
      ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

      CREATE TABLE IF NOT EXISTS SESSION(
      SESSION_ID INT(32),
      COURSE_ID INT(32),
      TOTAL_ENROLLED INT,
      TOTAL_FEES FLOAT,
      MAX_CAPACITY INT,
      PRIMARY KEY (SESSION_ID)
      ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

      CREATE TABLE IF NOT EXISTS PLACEMENT(
        OPENING_ID INT(32),
        CANDIDATE_ID INT(32),
        TOTAL_HOURS_WORKED FLOAT,
        PRIMARY KEY(OPENING_ID)
      ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
    

    ALTER TABLE CANDIDATE ADD FOREIGN KEY (CANDIDATE_ID) REFERENCES PLACEMENT(CANDIDATE_ID);
    ALTER TABLE CANDIDATE ADD FOREIGN KEY (CANDIDATE_ID) REFERENCES JOB_HISTORY(CANDIDATE_ID);
    
    ALTER TABLE OPENING ADD FOREIGN KEY (OPENING_ID) REFERENCES PLACEMENT(OPENING_ID);

    ALTER TABLE COMPANY ADD FOREIGN KEY (COMPANY_ID) REFERENCES OPENING(COMPANY_ID);

    ALTER TABLE QUALIFICATION ADD FOREIGN KEY (QUALIFICATION_CODE) REFERENCES COURSE(QUALIFICATION_CODE);
    ALTER TABLE QUALIFICATION ADD FOREIGN KEY (QUALIFICATION_CODE) REFERENCES CANDIDATE(QUALIFICATION_CODE);

    ALTER TABLE COURSE ADD FOREIGN KEY (COURSE_ID) REFERENCES QUALIFICATION(COURSE_ID);
    ALTER TABLE COURSE ADD FOREIGN KEY (COURSE_ID) REFERENCES SESSION(COURSE_ID);
    
    ALTER TABLE SESSION ADD FOREIGN KEY (SESSION_ID) REFERENCES COURSE(SESSION_ID);
     ";

    if ($conn->multi_query($sql) === TRUE) 
    {
    echo "All tables created successfully";
    } else 
    {
    echo "<br> Couldn't create all tables: " . $conn->error;
    }


}