
<?php
require_once('database.php');
function Create_All_Tables()
{
    $conn = Connect_to_Database();
    $sql = "CREATE TABLE IF NOT EXISTS CANDIDATE(
        CANDIDATE_ID INT(32) UNIQUE NOT NULL,
        FIRST_NAME VARCHAR(30),
        LAST_NAME VARCHAR(30),
        AGE INT(32),
        SOCIAL_SECURITY VARCHAR(12),
        DATE_OF_REGRISTRATION DATE,
        PRIMARY KEY (CANDIDATE_ID)
    ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

    CREATE TABLE IF NOT EXISTS COMPANY(
        COMPANY_ID INT(32) UNIQUE NOT NULL,
        COMPANY_NAME VARCHAR(200),
        PRIMARY KEY (COMPANY_ID)
    ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

    CREATE TABLE IF NOT EXISTS COURSE(
        COURSE_ID INT(32),
        CURRENTLY_OFFERED BIT,
        PRIMARY KEY(COURSE_ID)
    ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

    CREATE TABLE IF NOT EXISTS JOB_HISTORY(
        CANDIDATE_ID INT(32),
        PAST_JOB VARCHAR(50),
        PRIMARY KEY (CANDIDATE_ID)
        ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

    CREATE TABLE IF NOT EXISTS OPENING(
        OPENING_ID INT(32),
        COMPANY_ID INT(32),
        STARTING_DATE DATE,
        REQUIRED_QUALIFICATIONS INT,
        MAIN_QUALIFICATION_CODE VARCHAR(20),
        PRIMARY KEY (OPENING_ID)
    ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

    CREATE TABLE IF NOT EXISTS QUALIFICATION(
        QUALIFICATION_CODE VARCHAR(20),
        CANDIDATE_ID INT(32),
        PRIMARY KEY (QUALIFICATION_CODE)
    ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

    CREATE TABLE IF NOT EXISTS SESSION(
            SESSION_ID INT(32),
            COURSE_ID INT(32),
            TOTAL_ENROLLED INT,
            TOTAL_FEES FLOAT,
            MAX_CAPACITY INT,
            STARTING_TIME DATETIME,
            ENDING_TIME DATETIME,
            PRIMARY KEY (SESSION_ID)
        ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

    CREATE TABLE IF NOT EXISTS PLACEMENT(
        OPENING_ID INT(32),
        CANDIDATE_ID INT(32),
        TOTAL_HOURS_WORKED FLOAT,
        PRIMARY KEY(CANDIDATE_ID, OPENING_ID)
    ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

    CREATE TABLE IF NOT EXISTS COURSE_PREREQ(
        QUALIFICATION_CODE VARCHAR(20),
        COURSE_ID INT(32),
        PRIMARY KEY (QUALIFICATION_CODE, COURSE_ID)
    ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


    CREATE TABLE IF NOT EXISTS Degree(
        QUALIFICATION_CODE VARCHAR(20),
        DESCRIPTION VARCHAR(200),
        PRIMARY KEY(QUALIFICATION_CODE)
    ) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
    
    -- ALTER TABLE PLACEMENT ADD CONSTRAINT FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATE(CANDIDATE_ID);
    
    -- ALTER TABLE JOB_HISTORY ADD CONSTRAINT FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATE(CANDIDATE_ID);

    -- ALTER TABLE OPENING ADD CONSTRAINT FOREIGN KEY (OPENING_ID) REFERENCES PLACEMENT(OPENING_ID);
    -- ALTER TABLE OPENING ADD CONSTRAINT FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(COMPANY_ID);
    
    -- ALTER TABLE COURSE ADD CONSTRAINT FOREIGN KEY (SESSION_ID) REFERENCES SESSION(SESSION_ID);
    -- ALTER TABLE COURSE ADD CONSTRAINT FOREIGN KEY (QUALIFICATION_CODE) REFERENCES QUALIFICATION(QUALIFICATION_CODE);
    
    -- ALTER TABLE QUALIFICATION ADD CONSTRAINT FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID);

    -- ALTER TABLE SESSION ADD CONSTRAINT FOREIGN KEY (COURSE_ID) REFERENCES QUALIFICATION(COURSE_ID);

    -- ALTER TABLE CANDIDATE ADD CONSTRAINT FOREIGN KEY (QUALIFICATION_CODE) REFERENCES QUALIFICATION(QUALIFICATION_CODE);
    
    ";

    if ($conn->multi_query($sql) === TRUE) 
    {
        echo "All tables created successfully";
    } else 
    {
        echo "<br> Couldn't create all tables: " . $conn->error;
    }
}